from enum import Enum


class Noti(Enum):
    KILL_WUMPUS = "KILL WUMPUS"
    DETECT_PIT = "DETECT PIT"
    COLLECT_GOLD = "COLLECT GOLD"
    SHOOT_ARROW = "SHOOT ARROW"
    PERCEIVE_BREEZE = "PERCEIVE BREEZE"
    PERCEIVE_STENCH = "PERCEIVE STENCH"
    KILL_NO_WUMPUS = 'KILL NO WUMPUS'
    KILL_BY_WUMPUS = 'KILLED BY WUMPUS'
    KILL_BY_PIT = 'KILLED BY PIT'
    CLIMB_OUT_OF_THE_CAVE = 'CLIMB OUT OF THE CAVE'
    DETECT_WUMPUS = 'DETECT WUMPUS'
    DETECT_NO_PIT = 'DETECT NO PIT'
    DETECT_NO_WUMPUS = 'DETECT NO WUMPUS'
    INFER_PIT = 'INFER PIT'
    INFER_WUMPUS = 'INFER WUMPUS'
    SHOOT_RANDOMLY = 'SHOOT RANDOMLY'
    FAIL_TO_INFER_PIT = 'FAIL TO INFER PIT'
